"""Centralized frozen constants from SPEC 1.0."""

from math import log

SUBJECTIVE_MODEL_VERSION = 1
HISTORY_MODEL_VERSION = 1
HISTORY_GATE_VERSION = 1
ODDS_ANALYSIS_VERSION = 1
STATS_VERSION = 1

FLOAT_EPSILON = 1e-12

JEFFREYS_ALPHA = 0.5
JEFFREYS_BETA = 0.5
HISTORY_CREDIBLE_LEVEL = 0.95
HISTORY_MIN_SAMPLE_SIZE = 20
HISTORY_MAX_INTERVAL_WIDTH = 0.25

SUBJECTIVE_MIN_PROBABILITY = 0.01
SUBJECTIVE_LOW_BREAKPOINT = 0.45
SUBJECTIVE_MID_HIGH_BREAKPOINT = 0.55
SUBJECTIVE_HIGH_BREAKPOINT = 0.85
SUBJECTIVE_VERY_HIGH_BREAKPOINT = 0.95
SUBJECTIVE_MAX_PROBABILITY = 0.99

SUBJECTIVE_FACTOR_LOW = 1.5
SUBJECTIVE_FACTOR_MID = 2.0
SUBJECTIVE_FACTOR_HIGH = 1.4
SUBJECTIVE_FACTOR_MAX = 1.2

LOG_FACTOR_LOW = log(SUBJECTIVE_FACTOR_LOW)
LOG_FACTOR_MID = log(SUBJECTIVE_FACTOR_MID)
LOG_FACTOR_HIGH = log(SUBJECTIVE_FACTOR_HIGH)
LOG_FACTOR_MAX = log(SUBJECTIVE_FACTOR_MAX)
