"""Frozen character identities from SPEC 1.0 section 6."""

CHARACTERS = (
    (1, "isaac", "Isaac", 0, 1),
    (18, "tainted_isaac", "Tainted Isaac", 1, 1),
    (2, "magdalene", "Magdalene", 0, 2),
    (19, "tainted_magdalene", "Tainted Magdalene", 1, 2),
    (3, "cain", "Cain", 0, 3),
    (20, "tainted_cain", "Tainted Cain", 1, 3),
    (4, "judas", "Judas", 0, 4),
    (21, "tainted_judas", "Tainted Judas", 1, 4),
    (5, "blue_baby", "???", 0, 5),
    (22, "tainted_blue_baby", "Tainted ???", 1, 5),
    (6, "eve", "Eve", 0, 6),
    (23, "tainted_eve", "Tainted Eve", 1, 6),
    (7, "samson", "Samson", 0, 7),
    (24, "tainted_samson", "Tainted Samson", 1, 7),
    (8, "azazel", "Azazel", 0, 8),
    (25, "tainted_azazel", "Tainted Azazel", 1, 8),
    (9, "lazarus", "Lazarus", 0, 9),
    (26, "tainted_lazarus", "Tainted Lazarus", 1, 9),
    (10, "eden", "Eden", 0, 10),
    (27, "tainted_eden", "Tainted Eden", 1, 10),
    (11, "the_lost", "The Lost", 0, 11),
    (28, "tainted_lost", "Tainted Lost", 1, 11),
    (12, "lilith", "Lilith", 0, 12),
    (29, "tainted_lilith", "Tainted Lilith", 1, 12),
    (13, "keeper", "Keeper", 0, 13),
    (30, "tainted_keeper", "Tainted Keeper", 1, 13),
    (14, "apollyon", "Apollyon", 0, 14),
    (31, "tainted_apollyon", "Tainted Apollyon", 1, 14),
    (15, "the_forgotten", "The Forgotten", 0, 15),
    (32, "tainted_forgotten", "Tainted Forgotten", 1, 15),
    (16, "bethany", "Bethany", 0, 16),
    (33, "tainted_bethany", "Tainted Bethany", 1, 16),
    (17, "jacob_and_esau", "Jacob & Esau", 0, 17),
    (34, "tainted_jacob", "Tainted Jacob", 1, 17),
)
